export const SET_USERINFO_DETAIL = "SET_USERINFO_DETAIL"; //设置用户信息
export const SET_USER_TYPE = "setUserType"; //用户类型
export const GET_TEACHER_INFO = "GET_TEACHER_INFO"; //获取教职工信息
export const GET_USER_INFO = "getUserInfo"; //获取用户表格信息
export const GET_USER_DEPT = "getUserDept"; //获取用户部门/院系
export const GET_USER_DEPT_OLD = "GET_USER_DEPT_OLD"; //获取用户部门/院系（老）
export const GET_USER_DEPT_TEACH = "GET_USER_DEPT_TEACH"; //获取获取老师部门
export const GET_USER_MAJOR = "getUserMajor"; //获取用户专业
export const GET_USER_MAJOR_OLD = "GET_USER_MAJOR_OLD"; //获取用户专业(老)
export const GET_USER_TYPE = "getUserType"; //获取人员类型
export const GET_USER_STU = "GET_USER_STU"; //获取学生类型
export const GET_USER_TEACH = "GET_USER_TEACH"; //获取老师类型
export const GET_USER_SEX = "GET_USER_SEX"; //获取性别
export const GET_CLASS_LIST = "GET_CLASS_LIST"; //获取班级
export const GET_STU_CATEGORY = "GET_STU_CATEGORY"; //获取培养层次
export const GET_USER_STATUS = "getUserStatus"; //获取账号状态
export const DEL_USER = "delUser"; //删除用户
export const EXPORT_USER = "exportUser"; //导出用户
export const SET_USER_STATUS = "setUserStatus"; //设置用户状态
export const SET_USER_PASSWD = "setUserPasswd"; //设置用户密码
export const ADD_USER = "ADD_USER"; //新增用户
export const GET_ADMIN_WID = "GET_ADMIN_WID"; //获取管理员wid

// 安全设置
export const GET_SECURITY = "GET_SECURITY"; //获取租户安全设置
export const CHECK_ADMIN_PHONE = "CHECK_ADMIN_PHONE"; //检测admin是否绑定邮箱或者手机号
export const GET_CODE = "GET_CODE"; //获取验证码 params:{cellphone:string}
export const CHECK_CODE = "CHECK_CODE"; //验证验证码 params:{cellphone:string，code:string}
export const HAS_CODE = "HAS_CODE"; //是否已经有验证码 params:{cellphone:string}
export const SET_PHONE = "SET_PHONE"; //是否已经有验证码 params:{cellphone:string}
export const CONTINUE = "CONTINUE"; //触发继续操作
